imu_topic: /livox/imu

imu_excite_threshold: 0.5
gravity_mag: 9.81

# Livox IMU is normalized to 1 g.
if_normalized: true

if_use_init_bg: false

IMUExtrinsics:  # imu to imu
    Trans: [0, 0, 0]
    Rot: [1, 0, 0,
          0, 1, 0,
          0, 0, 1]
